import { writeFileSync } from 'fs';
import { join } from 'path';
/**
 * @param {Object[]} object - can be any object or array of object generated by a js script.
 * @param {string} targetDir - the PATH to the location of the final JSON file.
 * @param {string} name - is the name of the created JSON file containing the objects.
 */

export function createJSON(object, targetDir, name) {
  const destination = join(targetDir, name);
  writeFileSync(destination, JSON.stringify(object, undefined, 2));
}
